version: '3'

services:

  hub:
    image: gridappsd/cimhub:1.1.0
    stdin_open: true
    tty: true
    volumes:
#      - ../Powergrid-Models/platform:/platform
#      - ../atptools/OEDI:/atp
      - /media/sf_src/atptools:/atp

