Results from base
THDi PV1    =  33.43 %
THDi PV2    = 137.56 %
THDi LOAD1  =   7.29 %
THDi LOAD2  = 107.40 %
THDi GEN1   =  10.86 %
THDi GEN2   =   8.39 %
THDi BESS1  =   4.52 %
THDi BESS2  =  60.54 %
Results from dssa
THDi PV1    =  33.43 %
THDi PV2    = 137.56 %
THDi LOAD1  =   7.29 %
THDi LOAD2  = 107.40 %
THDi GEN1   =  10.86 %
THDi GEN2   =   8.39 %
THDi BESS1  =   4.52 %
THDi BESS2  =  60.54 %
